version: '3.8'

services:
  backend:
    build:
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./backend:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development

  booking:
    build:
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./booking:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development

  address:
    build:
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./address:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development

  frontend:
    build:
      target: dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development

  gateway:
    build:
      target: dev
    command: npm run start:dev
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
