version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./backend:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://user:password@postgres:5432/backend_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379

  booking:
    build:
      context: .
      dockerfile: booking/Dockerfile
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./booking:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4001
      DATABASE_URL: postgresql://user:password@postgres:5432/booking_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_BUCKET_NAME: rooms-bucket
      AWS_FORCE_PATH_STYLE: "true"

  address:
    build:
      context: .
      dockerfile: address/Dockerfile
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./address:/app
      - ./proto:/app/proto
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4002
      DATABASE_URL: postgresql://user:password@postgres:5432/address_db?schema=public
      REDIS_HOST: redis
      REDIS_PORT: 6379

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      target: dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    extra_hosts:
      - "localhost:host-gateway"

  notification:
    build:
      context: .
      dockerfile: notification/Dockerfile
      target: dev
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    volumes:
      - ./notification:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 4003
      DATABASE_URL: postgresql://user:password@postgres:5432/notification_db?schema=public
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672
    ports:
      - "4003:4003"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
      target: dev
    command: npm run start:dev
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      BACKEND_SERVICE_URL: http://backend:4000
      BOOKING_SERVICE_URL: http://booking:4001
      ADDRESS_SERVICE_URL: http://address:4002
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_S3_ENDPOINT: http://localstack:4566
      PUBLIC_S3_ENDPOINT: http://localhost:4566
      AWS_BUCKET_NAME: rooms-bucket
      AWS_FORCE_PATH_STYLE: "true"
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_ERLANG_COOKIE: "secretcookie1234567890"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services port range
    environment:
      - SERVICES=s3
      - DEBUG=1
      - PERSISTENCE=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./localstack_data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

